### PR TITLE
fixed the css for speciality

### PR DESCRIPTION
**Pull request by andrewphan1**
Screenshot 2023-05-25 at 9 17 28 PM

I made css changes to the speciality page

### CODE REVIEW

**Review by Kameronjan — APPROVED** [review]
Looking good!

**Review by Kameronjan — COMMENTED** [review]
Seems like there are a few conflicts that need to be resolved

**Review by Version-LAA — APPROVED** [review]
Looks good! I removed the specialty pages that no longer exist.

**Review by Kameronjan — COMMENTED** [review]
Nice!

**Pull request merged**
